server:
  port: 8086

spring:
  application:
    name: audit-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/tatva}
    username: ${POSTGRES_USER:tatva}
    password: ${POSTGRES_PASSWORD:tatva_pg_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: tatva-audit-cg
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    path: /api/audit/v3/api-docs
  swagger-ui:
    path: /api/audit/swagger-ui.html

logging:
  level:
    com.tatva.audit: DEBUG
    org.hibernate.SQL: DEBUG
