"""
TATVA — Hallucination Detector.

Compares LLM-generated output against known entities in the graph.
If > 30% of mentioned entities are NOT in the graph, flags as hallucinated.
"""

from __future__ import annotations

import re
from typing import FrozenSet, List, Set, Tuple


def extract_entity_names_from_text(text: str) -> List[str]:
    """
    Extract potential entity names from LLM output.

    Uses heuristics: capitalised multi-word phrases, quoted strings,
    and known patterns.
    """
    entities: List[str] = []

    # Match capitalised multi-word sequences (e.g., "Indian Air Force")
    cap_pattern = re.compile(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\b")
    entities.extend(cap_pattern.findall(text))

    # Match all-caps acronyms (e.g., "DRDO", "NATO")
    acronym_pattern = re.compile(r"\b([A-Z]{2,6})\b")
    entities.extend(acronym_pattern.findall(text))

    # Match quoted strings (LLM often quotes entity names)
    quoted_pattern = re.compile(r"['\"]([A-Z][^'\"]{2,50})['\"]")
    entities.extend(quoted_pattern.findall(text))

    # Deduplicate while preserving order
    seen: Set[str] = set()
    unique: List[str] = []
    for e in entities:
        lower = e.lower()
        if lower not in seen:
            seen.add(lower)
            unique.append(e)

    return unique


def detect_hallucination(
    llm_output: str,
    known_entities: FrozenSet[str],
    threshold: float = 0.30,
) -> Tuple[bool, float, List[str]]:
    """
    Detect if the LLM output contains hallucinated entities.

    Args:
        llm_output: The text generated by the LLM.
        known_entities: Set of entity names known to exist in the graph
                        (lowercase normalised).
        threshold: Fraction of unknown entities that triggers a flag.

    Returns:
        (is_hallucinated, hallucination_rate, unknown_entities)
    """
    mentioned = extract_entity_names_from_text(llm_output)

    if not mentioned:
        return False, 0.0, []

    unknown: List[str] = []
    for entity in mentioned:
        if entity.lower() not in known_entities:
            unknown.append(entity)

    rate = len(unknown) / len(mentioned) if mentioned else 0.0
    is_hallucinated = rate > threshold

    return is_hallucinated, rate, unknown
