server:
  port: 8081

spring:
  application:
    name: ingestion-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/tatva}
    username: ${POSTGRES_USER:tatva}
    password: ${POSTGRES_PASSWORD:tatva_pg_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: tatva-ingestion-cg
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

springdoc:
  api-docs:
    path: /api/ingestion/v3/api-docs
  swagger-ui:
    path: /api/ingestion/swagger-ui.html

logging:
  level:
    com.tatva.ingestion: DEBUG
    org.hibernate.SQL: DEBUG
